name: Build and test app

on:
    workflow_dispatch:
    pull_request:
        branches: [main]
    push:
        branches: [main]


jobs:
    build_test:
        name: Run ${{matrix.os}} ${{matrix.node-version}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-20.04]
                node-version: [19.x, 20.x]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}
                cache: npm
            - name: Install dependecies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Test
              run: npm test
        