name: Contrast Security SCA
on:
    workflow_dispatch:
    schedule:
        - cron: "0 21 * * SUN"
    pull_request: 
        branches: [main]
jobs:
    Check-Dependency-Vulnerabilities:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - run: cat package.json
            - name: Contrast SCA action
              uses: Contrast-Security-OSS/contrast-sca-action@v1
              with:
                apiKey: ${{ secrets.CONTRAST_API_KEY }}
                orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
                authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
                apiUrl: ${{ secrets.CONTRAST_API_URL }}
                filePath: ./package.json
                severity: medium
                fail: true
